### ISSUE TITLE
师傅能配个ubuntu16的docker吗

### ISSUE THREAD

**Issue by N0zoM1z0** [RoderickChan/docker_pwn_env#2]

**Comment by RoderickChan** [comment]
> _No description provided._

可以，有空我配一个，到时候更新到项目里面

**Comment by N0zoM1z0** [comment]
> > _No description provided._
> 
> 可以，有空我配一个，到时候更新到项目里面

好的 谢谢师傅!

**Comment by RoderickChan** [comment]
> > > _No description provided._
> > 
> > 
> > 可以，有空我配一个，到时候更新到项目里面
> 
> 好的 谢谢师傅!

已更新镜像，使用`docker pull roderickchan/debug_pwn_env:16.04-2.23-0ubuntu11.3-20240412`拉取使用
