### ISSUE TITLE
2.35-0ubuntu3.1环境缺少sudo

### ISSUE THREAD

**Issue by RocketMaDev** [RoderickChan/docker_pwn_env#3]
2.35-0ubuntu3.1的环境是不是太远古了没有统一啊，没有sudo，没有zsh，用户还是roderick，遇到题了开起来发现pwndbg的setup因为没有sudo都跑不了

不知道师傅可不可以完善一下？

**Comment by RoderickChan** [comment]
> 2.35-0ubuntu3.1的环境是不是太远古了没有统一啊，没有sudo，没有zsh，用户还是roderick，遇到题了开起来发现pwndbg的setup因为没有sudo都跑不了
> 
> 不知道师傅可不可以完善一下？

是的，这个太古老了，没法更新，因为一更新就会自动更改glibc的版本。里面是装了pwndbg/gef之类的，只不过版本比较旧，应该不影响调试题目。

**Comment by RocketMaDev** [comment]
事实上pwndbg无法使用，因为没有sudo，setup.sh安装无法完成，一启动gdb就自动退出了

**Comment by RoderickChan** [comment]
> 事实上pwndbg无法使用，因为没有sudo，setup.sh安装无法完成，一启动gdb就自动退出了

我的意思是已经安装好了pwndbg，直接使用即可，不需要安装。如下图所示，是可以使用的：

![image](https://github.com/RoderickChan/docker_pwn_env/assets/50228047/adcd4662-fc50-46f4-bce8-7d6af16c3ff7)

**Comment by RocketMaDev** [comment]
@RoderickChan 由于上述的问题，我只能从容器里拉取libc相关文件到本地，然后patchelf后做，但仍有2个小问题希望得到师傅解答：

- 虽然我从容器中拉取了`/usr/lib/debug`目录到本地`~/glibc-all-in-one/libs/2.35-0ubuntu3.1_amd64/.debug`并将其软链接到需调试文件目录下，但无论我是直接启动gdb或是在gdb中设置调试文件目录（上述目录中的.debug和.debug/.build-id都试过），使用`info share`都显示找不到libc的调试信息，怎样正确加载调试信息？

- 我本地环境是Arch Linux，在调试到libc的部分时，pwndbg会自动帮我下载源码并显示在code section中，可是patchelf后始终无法下载源码，（远程连接已重置）有没有办法可以修正这一行为？

**Comment by RocketMaDev** [comment]
> > 事实上pwndbg无法使用，因为没有sudo，setup.sh安装无法完成，一启动gdb就自动退出了
> 
> 我的意思是已经安装好了pwndbg，直接使用即可，不需要安装。如下图所示，是可以使用的：
> 
> ![image](https://github.com/RoderickChan/docker_pwn_env/assets/50228047/adcd4662-fc50-46f4-bce8-7d6af16c3ff7)
> 

I'll check it later.

**Comment by RoderickChan** [comment]
> @RoderickChan 由于上述的问题，我只能从容器里拉取libc相关文件到本地，然后patchelf后做，但仍有2个小问题希望得到师傅解答：
> 
> * 虽然我从容器中拉取了`/usr/lib/debug`目录到本地`~/glibc-all-in-one/libs/2.35-0ubuntu3.1_amd64/.debug`并将其软链接到需调试文件目录下，但无论我是直接启动gdb或是在gdb中设置调试文件目录（上述目录中的.debug和.debug/.build-id都试过），使用`info share`都显示找不到libc的调试信息，怎样正确加载调试信息？
> * 我本地环境是Arch Linux，在调试到libc的部分时，pwndbg会自动帮我下载源码并显示在code section中，可是patchelf后始终无法下载源码，（远程连接已重置）有没有办法可以修正这一行为？

首先，我试了下roderickchan/debug_pwn_env:22.04-2.35-0ubuntu3.1-20230213这个镜像，是没有问题的，可以调试。如果需要源码调试glibc的话，手动下载对应的源码放到容器里面，然后使用directory添加搜索路径即可。

其次，针对你的问题，可以手动下载这个版本的调试符号，然后再加载到gdb里面试试。或者可以使用`pwnlib.libcdb.unstrip_libc`这个接口试试。至于下载源码的问题，可以搜搜pwndbg的issue，我没遇到过。

**Comment by RocketMaDev** [comment]
![屏幕截图_20240508_123506](https://github.com/RoderickChan/docker_pwn_env/assets/48864431/fa93d0a1-ce67-412c-b207-de5af99ed4a2)

我启动gdb以后是这样的

**Comment by RocketMaDev** [comment]
好了，我找到问题了

![屏幕截图_20240508_123732](https://github.com/RoderickChan/docker_pwn_env/assets/48864431/de2a0f0c-6fcc-42b6-a7d5-0427dd83d670)

之前我用的时候没加后面的/bin/bash

**Comment by RocketMaDev** [comment]
看来是auto update导致的

**Comment by RoderickChan** [comment]
嗯嗯，太老的版本不能auto update。使用过程中有其他问题可随时交流🤝



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 中午12:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RoderickChan/docker_pwn_env] 2.35-0ubuntu3.1环境缺少sudo (Issue #3)




 
好了，我找到问题了
 
_20240508_123732.png (view on web)
 
之前我用的时候没加后面的/bin/bash

**Comment by RocketMaDev** [comment]
动态源码是由debuginfod提供的，因此与pwndbg无关。要想在patchelf后看到源码，需要配置一下gdb中的debuginfod

![屏幕截图_20240508_130243](https://github.com/RoderickChan/docker_pwn_env/assets/48864431/39147194-a4fb-480b-946b-58ab66014c7b)

**Comment by RocketMaDev** [comment]
看了一下，ubuntu的debuginfod还没有提供源代码，[官网](https://ubuntu.com/server/docs/about-debuginfod)是这么说的：
> Currently, the service only provides DWARF information. There are plans for it to also index and serve source-code in the future.

:(

**Comment by RocketMaDev** [comment]
提一句别的，刚刚在复习house of apple的时候看到了一个问题：

![屏幕截图_20240508_164604](https://github.com/RoderickChan/docker_pwn_env/assets/48864431/f53e34c0-4ff2-4a1c-9b6e-64a05941cfb2)

`fp->_wide_data->_IO_buf_base`应该要等于0吧，否则就return了
@RoderickChan

**Comment by RoderickChan** [comment]
> 提一句别的，刚刚在复习house of apple的时候看到了一个问题：
> 
> ![屏幕截图_20240508_164604](https://private-user-images.githubusercontent.com/48864431/328820667-f53e34c0-4ff2-4a1c-9b6e-64a05941cfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjA2OTYsIm5iZiI6MTcxNTE2MDM5NiwicGF0aCI6Ii80ODg2NDQzMS8zMjg4MjA2NjctZjUzZTM0YzAtNGZmMi00YTFjLTliNmUtNjRhMDU5NDFjZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGUyZTEyNTJlMGQwOTljMTgzMGQwZWY1MTAwODhlOTA4OTc0NjYyMTgzZjlhZTU4ZjMxYTQ4NGE4MjQ2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JV_56TBw1ScZ1mCBEGuzwI5ylxkNc00SCB0xPb9Dyk8)
> 
> `fp->_wide_data->_IO_buf_base`应该要等于0吧，否则就return了 @RoderickChan

是的，应该是笔误
